package lexer;
 
/**
 *  This file is automatically generated<br>
 *  - it contains the enumeration of all of the tokens
*/
public enum Tokens {
  BogusToken,Program,Int,BOOLean,Char,
    CharLit,StringType,StringLit,If,Then,
    Else,Switch,Case,Colon,Default,
    While,Function,Return,Identifier,INTeger,
    LeftBrace,RightBrace,LeftParen,RightParen,Comma,
    Assign,Equal,NotEqual,Greater,GreaterEqual,
    Less,LessEqual,Plus,Minus,Or,
    And,Multiply,Divide,Comment,EndProgram,Invalid
}
